### ISSUE TITLE
race condition in queue tests

### ISSUE THREAD

**Issue by baerrach** [NicolasPetton/Indium#225]
I've modified `server/spec/helpers/queue-spec.js` to only run one test using `fit`:
```
fit("should run again when adding new workers", (done) => {
```

Then ran the test using `jasmine --random=true --seed=35084`

Sometimes it works.

When it fails I get this message:

```
Failures:
1) Running queues should run again when adding new workers
  Message:
    Expected $.length = 2 to equal 3.
    Expected $[2] = undefined to equal 3.
  Stack:
    Error: Expected $.length = 2 to equal 3.
        at <Jasmine>
        at Timeout.setTimeout [as _onTimeout] (C:\ide\Indium\server\spec\helpers\queue-spec.js:52:19)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
```

**Comment by baerrach** [comment]
```
$ node --version
v10.16.3
```

**Comment by baerrach** [comment]
Hacking in a `console.log` and praying for a failure prints
```
result [ 1, 2 ]
```

**Comment by baerrach** [comment]
The queue implementation used `setTimeout`, so the tests could never check whether the added tasks were completed.
